[package]
name = "rake"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"

rakelog = {path="./rakelog"}
rakedisplay = {path="./rakedisplay"}
rakemodel = {path="./rakemodel"}
rakeaudio = {path="./rakeaudio"}
cursive = "0.21.1"
rand = "0.9.1"
rodio = "0.20.1"
